from django.db import models
# from django.conf import settings



class ToCsv2(models.Model):
    EMP_NO = models.TextField(db_column='EMP_NO', blank=True,primary_key=True)  # Field name made lowercase.
    JOB_SITUATION1 = models.TextField(db_column='JOB_SITUATION1', blank=True, null=True)  # Field name made lowercase.
    JOB_SITUATION = models.BigIntegerField(db_column='JOB_SITUATION', blank=True, null=True)  # Field name made lowercase.
    NAME = models.TextField(db_column='NAME', blank=True, null=True)  # Field name made lowercase.
    SEX1 = models.TextField(db_column='SEX1', blank=True, null=True)  # Field name made lowercase.
    SEX = models.BigIntegerField(db_column='SEX', blank=True, null=True)  # Field name made lowercase.
    BIRTH_DATE = models.TextField(db_column='BIRTH_DATE', blank=True, null=True)  # Field name made lowercase.
    AGE = models.BigIntegerField(db_column='AGE', blank=True, null=True)  # Field name made lowercase.
    IN_CONPANY_DATE = models.TextField(db_column='IN_CONPANY_DATE', blank=True, null=True)  # Field name made lowercase.
    HIRE_YEAR = models.FloatField(db_column='HIRE_YEAR', blank=True, null=True)  # Field name made lowercase.
    CLASS_START_DAY = models.TextField(db_column='CLASS_START_DAY', blank=True, null=True)  # Field name made lowercase.
    CLASS_YEAR = models.FloatField(db_column='CLASS_YEAR', blank=True, null=True)  # Field name made lowercase.
    CURRENT_GRADE1 = models.TextField(db_column='CURRENT_GRADE1', blank=True, null=True)  # Field name made lowercase.
    CURRENT_GRADE = models.FloatField(db_column='CURRENT_GRADE', blank=True, null=True)  # Field name made lowercase.
    CURRENT_GRADE_1 = models.FloatField(db_column='CURRENT_GRADE_1', blank=True, null=True)  # Field name made lowercase.
    CURRENT_GRADE_2 = models.FloatField(db_column='CURRENT_GRADE_2', blank=True, null=True)  # Field name made lowercase.
    CURRENT_GRADE_3 = models.FloatField(db_column='CURRENT_GRADE_3', blank=True, null=True)  # Field name made lowercase.
    CURRENT_GRADE_4 = models.FloatField(db_column='CURRENT_GRADE_4', blank=True, null=True)  # Field name made lowercase.
    CLASS1 = models.TextField(db_column='CLASS1', blank=True, null=True)  # Field name made lowercase.
    CLASS_RANK = models.BigIntegerField(db_column='CLASS_RANK', blank=True, null=True)  # Field name made lowercase.
    CLASS_1 = models.BigIntegerField(db_column='CLASS_1', blank=True, null=True)  # Field name made lowercase.
    CLASS_2 = models.BigIntegerField(db_column='CLASS_2', blank=True, null=True)  # Field name made lowercase.
    CLASS_3 = models.BigIntegerField(db_column='CLASS_3', blank=True, null=True)  # Field name made lowercase.
    CLASS_4 = models.BigIntegerField(db_column='CLASS_4', blank=True, null=True)  # Field name made lowercase.
    CLASS_5 = models.BigIntegerField(db_column='CLASS_5', blank=True, null=True)  # Field name made lowercase.
    CLASS_6 = models.BigIntegerField(db_column='CLASS_6', blank=True, null=True)  # Field name made lowercase.
    CLASS_7 = models.BigIntegerField(db_column='CLASS_7', blank=True, null=True)  # Field name made lowercase.
    CLASS_8 = models.BigIntegerField(db_column='CLASS_8', blank=True, null=True)  # Field name made lowercase.
    CLASS_9 = models.BigIntegerField(db_column='CLASS_9', blank=True, null=True)  # Field name made lowercase.
    CLASS_10 = models.BigIntegerField(db_column='CLASS_10', blank=True, null=True)  # Field name made lowercase.
    CLASS_11 = models.BigIntegerField(db_column='CLASS_11', blank=True, null=True)  # Field name made lowercase.
    CLASS_12 = models.BigIntegerField(db_column='CLASS_12', blank=True, null=True)  # Field name made lowercase.
    CLASS_13 = models.BigIntegerField(db_column='CLASS_13', blank=True, null=True)  # Field name made lowercase.
    CLASS_14 = models.BigIntegerField(db_column='CLASS_14', blank=True, null=True)  # Field name made lowercase.
    CLASS_15 = models.BigIntegerField(db_column='CLASS_15', blank=True, null=True)  # Field name made lowercase.
    CLASS_16 = models.BigIntegerField(db_column='CLASS_16', blank=True, null=True)  # Field name made lowercase.
    CLASS_17 = models.BigIntegerField(db_column='CLASS_17', blank=True, null=True)  # Field name made lowercase.
    CLASS_18 = models.BigIntegerField(db_column='CLASS_18', blank=True, null=True)  # Field name made lowercase.
    CLASS_19 = models.BigIntegerField(db_column='CLASS_19', blank=True, null=True)  # Field name made lowercase.
    CLASS_20 = models.BigIntegerField(db_column='CLASS_20', blank=True, null=True)  # Field name made lowercase.
    WAGE = models.FloatField(db_column='WAGE', blank=True, null=True)  # Field name made lowercase.
    EDUCATION_NAME1 = models.TextField(db_column='EDUCATION_NAME1', blank=True, null=True)  # Field name made lowercase.
    EDUCATION_NAME = models.BigIntegerField(db_column='EDUCATION_NAME', blank=True, null=True)  # Field name made lowercase.
    EDUCATION_NAME_1 = models.BigIntegerField(db_column='EDUCATION_NAME_1', blank=True, null=True)  # Field name made lowercase.
    EDUCATION_NAME_2 = models.BigIntegerField(db_column='EDUCATION_NAME_2', blank=True, null=True)  # Field name made lowercase.
    EDUCATION_NAME_3 = models.BigIntegerField(db_column='EDUCATION_NAME_3', blank=True, null=True)  # Field name made lowercase.
    EDUCATION_NAME_4 = models.BigIntegerField(db_column='EDUCATION_NAME_4', blank=True, null=True)  # Field name made lowercase.
    EDUCATION_NAME_5 = models.BigIntegerField(db_column='EDUCATION_NAME_5', blank=True, null=True)  # Field name made lowercase.
    EDUCATION_NAME_6 = models.BigIntegerField(db_column='EDUCATION_NAME_6', blank=True, null=True)  # Field name made lowercase.
    EDUCATION_NAME_7 = models.BigIntegerField(db_column='EDUCATION_NAME_7', blank=True, null=True)  # Field name made lowercase.
    EDUCATION_NAME_8 = models.BigIntegerField(db_column='EDUCATION_NAME_8', blank=True, null=True)  # Field name made lowercase.
    GRADUATE_SCHOOL = models.TextField(db_column='GRADUATE_SCHOOL', blank=True, null=True)  # Field name made lowercase.
    GRADUATE_SPECIALTY = models.TextField(db_column='GRADUATE_SPECIALTY', blank=True, null=True)  # Field name made lowercase.
    MARRIED1 = models.TextField(db_column='MARRIED1', blank=True, null=True)  # Field name made lowercase.
    MARRIED = models.FloatField(db_column='MARRIED', blank=True, null=True)  # Field name made lowercase.
    MARRIED_1 = models.FloatField(db_column='MARRIED_1', blank=True, null=True)  # Field name made lowercase.
    MARRIED_2 = models.FloatField(db_column='MARRIED_2', blank=True, null=True)  # Field name made lowercase.
    JWH = models.TextField(db_column='JWH', blank=True, null=True)  # Field name made lowercase.
    JOB_TYPE1 = models.TextField(db_column='JOB_TYPE1', blank=True, null=True)  # Field name made lowercase.
    JOB_TYPE = models.BigIntegerField(db_column='JOB_TYPE', blank=True, null=True)  # Field name made lowercase.
    JOB_TYPE_1 = models.BigIntegerField(db_column='JOB_TYPE_1', blank=True, null=True)  # Field name made lowercase.
    JOB_TYPE_2 = models.BigIntegerField(db_column='JOB_TYPE_2', blank=True, null=True)  # Field name made lowercase.
    JOB_TYPE_3 = models.BigIntegerField(db_column='JOB_TYPE_3', blank=True, null=True)  # Field name made lowercase.
    JOB_TYPE_4 = models.BigIntegerField(db_column='JOB_TYPE_4', blank=True, null=True)  # Field name made lowercase.
    JOB_TYPE_5 = models.BigIntegerField(db_column='JOB_TYPE_5', blank=True, null=True)  # Field name made lowercase.
    JOB_TYPE_6 = models.BigIntegerField(db_column='JOB_TYPE_6', blank=True, null=True)  # Field name made lowercase.
    JOB_TYPE_7 = models.BigIntegerField(db_column='JOB_TYPE_7', blank=True, null=True)  # Field name made lowercase.
    JOB_TYPE_8 = models.BigIntegerField(db_column='JOB_TYPE_8', blank=True, null=True)  # Field name made lowercase.
    JOB_TYPE_9 = models.BigIntegerField(db_column='JOB_TYPE_9', blank=True, null=True)  # Field name made lowercase.
    JOB_TYPE_10 = models.BigIntegerField(db_column='JOB_TYPE_10', blank=True, null=True)  # Field name made lowercase.
    JOB_TYPE_11 = models.BigIntegerField(db_column='JOB_TYPE_11', blank=True, null=True)  # Field name made lowercase.
    JOB_TYPE_12 = models.BigIntegerField(db_column='JOB_TYPE_12', blank=True, null=True)  # Field name made lowercase.
    JOB_TYPE_13 = models.BigIntegerField(db_column='JOB_TYPE_13', blank=True, null=True)  # Field name made lowercase.
    PROVINCE_NAME = models.TextField(db_column='PROVINCE_NAME', blank=True, null=True)  # Field name made lowercase.
    PROVINCE_DISTANCE_RANK = models.FloatField(db_column='PROVINCE_DISTANCE_RANK', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD1 = models.TextField(db_column='HOUSEHOLD1', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_DISTANCE_RANK = models.FloatField(db_column='HOUSEHOLD_DISTANCE_RANK', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_h = models.TextField(db_column='HOUSEHOLD_H', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_1 = models.FloatField(db_column='HOUSEHOLD_1', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_2 = models.FloatField(db_column='HOUSEHOLD_2', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_3 = models.FloatField(db_column='HOUSEHOLD_3', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_4 = models.FloatField(db_column='HOUSEHOLD_4', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_5 = models.FloatField(db_column='HOUSEHOLD_5', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_6 = models.FloatField(db_column='HOUSEHOLD_6', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_7 = models.FloatField(db_column='HOUSEHOLD_7', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_8 = models.FloatField(db_column='HOUSEHOLD_8', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_9 = models.FloatField(db_column='HOUSEHOLD_9', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_10 = models.FloatField(db_column='HOUSEHOLD_10', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_11 = models.FloatField(db_column='HOUSEHOLD_11', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_12 = models.FloatField(db_column='HOUSEHOLD_12', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_13 = models.FloatField(db_column='HOUSEHOLD_13', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_14 = models.FloatField(db_column='HOUSEHOLD_14', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_15 = models.FloatField(db_column='HOUSEHOLD_15', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_16 = models.FloatField(db_column='HOUSEHOLD_16', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_17 = models.FloatField(db_column='HOUSEHOLD_17', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_18 = models.FloatField(db_column='HOUSEHOLD_18', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_19 = models.FloatField(db_column='HOUSEHOLD_19', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_20 = models.FloatField(db_column='HOUSEHOLD_20', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_21 = models.FloatField(db_column='HOUSEHOLD_21', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_22 = models.FloatField(db_column='HOUSEHOLD_22', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_23 = models.FloatField(db_column='HOUSEHOLD_23', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_24 = models.FloatField(db_column='HOUSEHOLD_24', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_25 = models.FloatField(db_column='HOUSEHOLD_25', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_26 = models.FloatField(db_column='HOUSEHOLD_26', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_27 = models.FloatField(db_column='HOUSEHOLD_27', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_28 = models.FloatField(db_column='HOUSEHOLD_28', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_29 = models.FloatField(db_column='HOUSEHOLD_29', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_30 = models.FloatField(db_column='HOUSEHOLD_30', blank=True, null=True)  # Field name made lowercase.
    HOUSEHOLD_31 = models.FloatField(db_column='HOUSEHOLD_31', blank=True, null=True)  # Field name made lowercase.
    HIRE_TYPE_NAME1 = models.TextField(db_column='HIRE_TYPE_NAME1', blank=True, null=True)  # Field name made lowercase.
    HIRE_TYPE_NAME = models.BigIntegerField(db_column='HIRE_TYPE_NAME', blank=True, null=True)  # Field name made lowercase.
    HIRE_TYPENAME_1 = models.BigIntegerField(db_column='HIRE_TYPENAME_1', blank=True, null=True)  # Field name made lowercase.
    HIRE_TYPENAME_2 = models.BigIntegerField(db_column='HIRE_TYPENAME_2', blank=True, null=True)  # Field name made lowercase.
    WORKTIME = models.FloatField(db_column='WORKTIME', blank=True, null=True)  # Field name made lowercase.
    OT_TIME = models.FloatField(db_column='OT_TIME', blank=True, null=True)  # Field name made lowercase.
    BUSINESSTRIP_DAY = models.FloatField(db_column='BUSINESSTRIP_DAY', blank=True, null=True)  # Field name made lowercase.
    OFFICIALLEAVE_DAY = models.FloatField(db_column='OFFICIALLEAVE_DAY', blank=True, null=True)  # Field name made lowercase.
    LATEEXCUSED_DAY = models.FloatField(db_column='LATEEXCUSED_DAY', blank=True, null=True)  # Field name made lowercase.
    ABSENT_DAY = models.FloatField(db_column='ABSENT_DAY', blank=True, null=True)  # Field name made lowercase.
    DIMISSION_YEAR1 = models.FloatField(db_column='DIMISSION_YEAR1', blank=True, null=True)  # Field name made lowercase.
    DIMISSION_YEAR = models.TextField(db_column='DIMISSION_YEAR', blank=True, null=True)  # Field name made lowercase.
    ISNEW1 = models.TextField(db_column='ISNEW1', blank=True, null=True)  # Field name made lowercase.
    ISNEW = models.BigIntegerField(db_column='ISNEW', blank=True, null=True)  # Field name made lowercase.
    IS_GJRC1 = models.TextField(db_column='IS_GJRC1', blank=True, null=True)  # Field name made lowercase.
    IS_GJRC = models.FloatField(db_column='IS_GJRC', blank=True, null=True)  # Field name made lowercase.
    MANAGESYSTEM = models.TextField(db_column='MANAGESYSTEM', blank=True, null=True)  # Field name made lowercase.
    DIMISSION_DATE = models.TextField(db_column='DIMISSION_DATE', blank=True, null=True)  # Field name made lowercase.
    IS_COMPLETED = models.TextField(db_column='IS_COMPLETED', blank=True, null=True)  # Field name made lowercase.
    DIMISSION_REASON_NAME = models.TextField(db_column='DIMISSION_REASON_NAME', blank=True, null=True)  # Field name made lowercase.
    DIMISSION_TYPE_NAME = models.TextField(db_column='DIMISSION_TYPE_NAME', blank=True, null=True)  # Field name made lowercase.
    PRED_LEAVE = models.FloatField(db_column='PRED_LEAVE', blank=True, null=True)  # Field name made lowercase.
    SUB_BG_NAME = models.TextField(db_column='SUB_BG_NAME', blank=True, null=True)  # Field name made lowercase.
    COL_BU_NAME = models.TextField(db_column='COL_BU_NAME', blank=True, null=True)  # Field name made lowercase.
    JOB_NAME = models.TextField(db_column='JOB_NAME', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'to_csv2'

